name: CI

on: push

jobs:
  verification:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install modules
        run: yarn
      - name: Run lint
        run: yarn lint
      - name: Run prettier
        run: yarn prettier-check
      - name: Run tests
        run: yarn test
